# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ff83ab04f9a860858e13c09a93c5af5dd7e00b3bf9cf5e7df5157314553929b8c4bb88fc6d221e42d9f41ac800a458e156ed5bbeb24693c51a661aa31b5d74b

test:
  secret_key_base: 11b81f4f5a408d4d8815bc4633b6a737633e4da2f6561eeb85d215763d1a27656577fe27eb623b2c3bf0aa2feaf0bc9f69459f730bd6017c77a1b236b4b2fc0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
